/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f0xx.h"
#include "me.h"
#include <stdint.h>

// ================= CONFIG =================
#define STARTUP_DELAY_SEC   10U
#define HOLD_SECONDS        10U

#define ADC_AVG_SAMPLES     20     // ADC averaging
//#define STEP_HYST           1      // ±1 step hysteresis


// ================= GLOBAL TIME =================
volatile uint32_t g_millis = 0;
volatile uint32_t g_seconds = 0;
static uint32_t tim3_period = 0;
static uint32_t led_off_time = 0;
static uint8_t sys_start =0;
uint16_t raw = 0;
uint8_t step = 0;
uint8_t current_step = 0;
uint8_t pending_step = 0;
uint16_t box=0;
uint32_t pwm_counter=0;


// ================= CLOCK INIT =================
static void Clock_Init_HSI_8MHz(void)
{
    RCC->CR |= RCC_CR_HSION;
    while (!(RCC->CR & RCC_CR_HSIRDY));

    RCC->CFGR &= ~RCC_CFGR_SW;
    RCC->CFGR |= RCC_CFGR_SW_HSI;

    while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI);
}




// ================= GPIO & PERIPHERAL CLOCK =================
static void Clock_GPIO_Init(void)
{
    RCC->AHBENR  |= (1<<17);                //Enable GPIOA clock
    RCC->APB2ENR |= (1<<9);                 //Enable ADC clock
    RCC->APB1ENR |= (1<<1)|(1<<8);          //Enablr TIM3,TIM14 clock

    // set PA0 as output = LED1
    GPIOA->MODER |= (1U<<0);
    GPIOA->MODER &= ~(1U<<1);

    // set PA2 as output = LED2
    GPIOA->MODER |= (1U<<4);
    GPIOA->MODER &= ~(1U<<5);

    // PA6 = OUTPUT LOW (avoid flaoting volatge at pin 6 before TIM3 init)
	GPIOA->MODER |=  (1U<<12);
	GPIOA->MODER &= ~(1U<<13);
	GPIOA->ODR   &= ~(1U<<6);   // LOW

    // Set PA7 as analog mode = ADC_IN7
    GPIOA->MODER |=(1U<<14);
    GPIOA->MODER |=(1U<<15);
}

// ================= ADC =================
static void ADC1_Init(void)
{
    /* Enable HSI14 for ADC */
    RCC->CR2 |= RCC_CR2_HSI14ON;

    //wait until the HSI for ADC is ready
    while (!(RCC->CR2 & RCC_CR2_HSI14RDY));

    //disable the ADC
    ADC1->CR &= ~(1<<1);

    //start the calliberation
    ADC1->CR |= (1<<31);

    //wait until the calliberation is completed
    while (ADC1->CR & (1<<31));

    // ADC default config: single conversion, software trigger
    ADC1->CFGR1 = 0;

    // Set ADC sampling time (input hold duration)
    ADC1->SMPR  = ADC_SMPR_SMP;

    // Select ADC channel 7 (ADC_IN7)
    ADC1->CHSELR = (1U<<7);

    //Enable the ADC
    ADC1->CR |= (1U<<0);

    //wait until the ADC is ready
    while (!(ADC1->ISR & (1U<<0)));
}

//=============ADC read===================
static uint16_t ADC1_Read(void)
{
	//start conversion
    ADC1->CR |= (1<<2);

    //wait until the conversion is completed
    while (!(ADC1->ISR & (1<<2)))
    {
    	__NOP();
    }

    //return value
     return ADC1->DR;
}

// =============ADC averaging =======================
static uint16_t ADC1_Read_Avg(void)
{
    uint32_t sum = 0;
    for (uint8_t i = 0; i < ADC_AVG_SAMPLES; i++)
        sum += ADC1_Read();

    box= (uint16_t)(sum / ADC_AVG_SAMPLES);
    return box;
}

// ================= PWM (TIM3 CH1) =================


static void TIM3_PWM_Init(uint32_t freq)
{
    uint32_t clk = 8000000U;   // HSI = 8 MHz
    uint32_t arr = clk / freq;

    TIM3->PSC = 0;
    TIM3->ARR = arr - 1;
    tim3_period = arr;

    TIM3->CCMR1 &= ~(3U<<0);          //CC1S   = 0    ->     Output compare mode
    TIM3->CCMR1 |= (6U << 4);         //OC1M   = 110  ->     PWM mode 1
    TIM3->CCMR1 |= (1<<3);            //OC1PE  = 1    ->     Preload enable
    TIM3->CCER  |= (1<<0);            //CC1E   = 1    ->     Channel enable

    TIM3->EGR |= (1<<0);              // update event

    //set PA6 to alternate function
	GPIOA->MODER &= ~(1<<12);
	GPIOA->MODER |= (1<<13);


	// clear PA6 to alternate function type to TIM3(CH1)
	GPIOA->AFR[0] &= ~(1U<<24);
	GPIOA->AFR[0] &= ~(1U<<25);
	GPIOA->AFR[0] &= ~(1U<<26);
	GPIOA->AFR[0] &= ~(1U<<27);


	//Set PA6  alternate function type to TIM3 (CH1)
	GPIOA->AFR[0] |= (1U<<24);
	GPIOA->AFR[0] &= ~(1U<<25);
	GPIOA->AFR[0] &= ~(1U<<26);
	GPIOA->AFR[0] &= ~(1U<<27);

    TIM3->CR1 |= (1<<0);              // timer start

}

static void PWM_Set(uint8_t percent)
{
    if (percent > 100)
    {
    	percent = 100;
    }
    TIM3->CCR1 = ((tim3_period ) * percent) / 100;
    pwm_counter++;
}

// ================= TIM14 ISR =================
void TIM14_IRQHandler(void)
{
    static uint16_t ms_cnt = 0;

    if (TIM14->SR & TIM_SR_UIF)
    {
        TIM14->SR &= ~TIM_SR_UIF;

        g_millis++;
        ms_cnt++;

        if (ms_cnt >= 1000)
        {
            ms_cnt = 0;
            g_seconds++;
        }
    }
}

/* ================= TIM14 (1ms tick) ================= */
static void TIM14_Init(void)
{
    TIM14->PSC = 79;
    TIM14->ARR = 99;
    TIM14->CNT = 0;

    TIM14->DIER |= (1<<0);
    TIM14->CR1  |= (1<<0);

    NVIC_SetPriority(TIM14_IRQn, 1);
    NVIC_EnableIRQ(TIM14_IRQn);
}

// ================= MAIN =================

    int main(void)
    {


    	Clock_Init_HSI_8MHz();
        Clock_GPIO_Init();
        GPIOA->ODR &= ~(1U << 2);   // PA2 = OFF initially
        ADC1_Init();
        TIM3_PWM_Init(20000);
        TIM14_Init();

        GPIOA->ODR |= (1U << 0);
        PWM_Set(0);

        uint32_t last_sec = 0;
        uint32_t hold = 0;

        while (1)
        {
        	// auto LED OFF after blink
			if (led_off_time && g_seconds >= led_off_time)
			{
				GPIOA->BSRR = (1U << 18);
				led_off_time = 0;
			}

            //Read ADC in every one seocnd
            if (g_seconds != last_sec)
            {
                last_sec = g_seconds;

                // Startup delay
                if (g_seconds < STARTUP_DELAY_SEC)
                    continue;

                raw = ADC1_Read_Avg();

                if(raw <= ADC_100)
                {
                	step = 0;   // 0 V
                }

                else if (raw <= ADC_1K)
                {
                	step = 1;   // 1 V
                }

                else if (raw <= ADC_2K)
                {
                	step = 2;   // 2 V
                }

                else if (raw <= ADC_3K)
                {
                	step = 3;   // 3 V
                }

                else if (raw <= ADC_4K)
                {
                	step = 4;   // 4 V
                }

                else if (raw <= ADC_5K)
                {
                	step = 5;   // 5 V
                }

                else if (raw <= ADC_6K)
                {
                	step = 6;   // 6 V
                }

                else if (raw <= ADC_7K)
                {
                	step = 7;   // 7 V
                }

                else if (raw <= ADC_8K)
                {
                	step = 8;   // 8 V
                }

                else if (raw <= ADC_9K)
                {
                	step = 9;   // 9 V
                }

                else
                {
                	step = 10;  // 10 V
                }


                // ---- Stable window
				if (step != current_step)

				{
					if (pending_step != step)
					{
						pending_step = step;
						hold = 0;
						if(!sys_start)
						{
							current_step =step;
							PWM_Set(current_step *10);

							// STATUS LED BLINK
							GPIOA->BSRR = (1U << 2);
							led_off_time = g_seconds + 1;
							sys_start = 1;
						}
					}

					else
					{
						hold++;
						if (hold >= HOLD_SECONDS)
						{
							current_step = step;
							PWM_Set(current_step * 10);

							// STATUS LED BLINK
							GPIOA->BSRR = (1U << 2);
							led_off_time = g_seconds + 1;

							pending_step = 0;
							hold = 0;
				         }
					}
				}


				else
				{

					pending_step = 0;
					hold = 0;
				}
			}

		}
	}
